# Generated by Django 4.2.5 on 2023-09-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
